sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t springdocker/sample1 .

deploy:
  provider: elasticbeanstalk
  region: 'ap-south-1'
  app: 'Docker'
  env: 'Docker-env'
  bucket_name: 'elasticbeanstalk-ap-south-1-116547797322'
  bucket_path: 'Docker'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
